### ISSUE TITLE
Sideload symlinked addons

### ISSUE THREAD

**Issue by sleeyax** [sungshon/PimpMyStremio#27]
Currently PMS doesn't read symlinked directories in the `sideload/` directory. It could be useful to add such a functionality in case someone likes to store add-ons on a separate drive for development.

https://github.com/sungshon/PimpMyStremio/blob/5c019c68dbe7f16b91d4e4186b7f27c8ecab6fb1/src/lib/sideload.js#L6-L7

I can open a pull request for this small issue if you're busy with other things, but I'd like to see your opinion on this first.

**Comment by sungshon** [comment]
I'm ok with such a change, I don't have any thoughts about it tbh.

Just that maybe it would also be useful to change the sideload directory based on a environment variable and maybe even a process client argument.

What I like about the env var is that users can set an OS wide env var, thus changing the sideload folder to whatever path they want forever.

**Comment by sungshon** [comment]
I'm also ok with a PR if you want to make one, otherwise I can also do it. I prefer people contributing though. (obviously)

**Comment by sleeyax** [comment]
I'll just submit a PR that fixes this particular issue. Setting an environment variable / CLI parameter is a great idea, but I suggest we create a new issue for that to keep things structured.

**Comment by sungshon** [comment]
will close as PR https://github.com/sungshon/PimpMyStremio/pull/30 fixes it
