### ISSUE TITLE
Default value can't be 0

### ISSUE THREAD

**Issue by sleeyax** [sungshon/PimpMyStremio#28]
I have a property in my config file of type `number` with a default value of `0`, like this:
```
 "minSeeders": {
    "title": "Minimum amount of seeders",
    "type": "number",
    "default": 0,
    "required": true
  },
```

The problem is that this line in you code always results in an empty string because 0 is equal to false in javascript:
https://github.com/sungshon/PimpMyStremio/blob/5c019c68dbe7f16b91d4e4186b7f27c8ecab6fb1/src/web/script.js#L258

...causing the UI to never display value 0 whenever the settings menu is opened:

![image](https://i.imgur.com/tCFHbu7.png)

**Comment by sungshon** [comment]
Yeah, the issue is pretty obvious, I guess `0` should be the only accepted truthy value, as an empty string should still be falsey, and `false` itself is only used with a checkbox element (which doesn't make sense to be set to required at all)

**Comment by sleeyax** [comment]
Okay, ill just create a PR for this too then

**Comment by sungshon** [comment]
will close as PR https://github.com/sungshon/PimpMyStremio/pull/30 fixes it
