### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by meroron** [sungshon/PimpMyStremio#42]
In what folder does PimpMyStremio download data so I can delete it?
I'm on MacOS.

**Comment by 1legendd** [comment]
how do i fully uninstall PimpMyStremio from my mac?

**Comment by 1legendd** [comment]
Hi but I can't find ~/Library/Preferences/PimpMyStremio folder. I have the app but not the content files for the folder? Not sure what happened

**Comment by cutewindows10** [comment]
I might be useless here, but for anyone searching on Google who found this: on **Windows**, it installs in the Roaming **AppData** folder. You can also use 'Everything Search'.

**Comment by KiraiEEE** [comment]
I might be useless here, but for anyone searching on Google who found this: on **Windows**, it installs in the Roaming **AppData** folder. You can also use 'Everything Search'.
