### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Aithaks** [sungshon/PimpMyStremio#43]
Hello,sorry to ask this question but how to run it on win 7 x64?I am quite new to this

**Comment by sungshon** [comment]
Download it from this link:
https://github.com/sungshon/PimpMyStremio/releases/download/v1.1.8/PimpMyStremio-win-x64.zip

After you run it will it will take some time to update, don't worry if it feels that it's taking too long to update, just wait it out.

Then follow this quickstart guide:
https://github.com/sungshon/PimpMyStremio/blob/master/docs/user-guide.md

**Comment by Aithaks** [comment]
Thanks for the reply,but whenever I try to run it,It just stays in the taskbar and does nothing.So,could you please help me out? @sungshon

**Comment by sungshon** [comment]
You need to press the taskbar icon and select "Show in Browser", alternatively you can also do this manually by just open a browser and going to http://127.0.0.1:7777/

**Comment by Aithaks** [comment]
I keep doing that,but still it's no use,any ideas to make it work? @sungshon

**Comment by sleeyax** [comment]
@Aithaks 

What do you mean it's no use? Do you get an error or doesn't it do anything at all?

**Comment by sleeyax** [comment]
Just installed PMS on my windows 7 x64 VM and it works fine. Maybe the default port `7777` is occupied by another process on your system? 

You can change the port in the following configuration file: `%APPDATA%\PimpMyStremio\PimpMyStremio-userConfig.json` 

(e.g. to change it to port `9999` -  `"Server port","type":"number","default":7777,"value":9999`)

**Comment by sungshon** [comment]
@sleeyax it can't be that, even if it has a closed port set in the settings, it will just pick the next open port it finds and start the server on that

@Aithaks it's very difficult to know what is wrong, or even if nothing is wrong at all and you are just expecting things to work differently, i should try:

- restarting your PC, opening PimpMyStremio again, waiting patiently for it to start and seeing if it acts differently
- run PimpMyStremio from the command line with the "--verbose" flag so it shows the logs in the command line, so we can learn what is wrong with it

**Comment by Aithaks** [comment]
I mean nothing happens even if I try and press open in browser.It doesn't respond anything,it just stays there @sleeyax

**Comment by Aithaks** [comment]
Sorry,but where do you enter the verbose flag?I am noob to this @sungshon

**Comment by Aithaks** [comment]
here is the output I got from cmd
"C:\Windows\system32>"C:\***\***\Desktop\PimpMyStremio.exe" --verbose
PimpMyStremio - Checking for updates
PimpMyStremio - Already have latest version
PimpMyStremio - User defined add-ons list URL is valid, updating add-ons list
PimpMyStremio - Successfully updated add-ons list from remote source
PimpMyStremio server running at: http://127.0.0.1:5080
Non-critical: Could not auto-open webpage, presuming Linux OS
{ Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1317:13)
    at startup (bootstrap_node.js:240:16)
    at bootstrap_node.js:661:3
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [ '/c', 'start', '""', '/b', '/wait', 'http://127.0.0.1:5080' ] }
systrayhelper 0.0.5 (d5794e2a72a9cb160d78b6fd9ee640ad1df02af7 built 2018-12-05T0
9:24:27Z)" @sungshon

**Comment by sungshon** [comment]
This is indeed a special case, the default port is being used and opening the default browser is failing for some reason on your system.

If you look in the logs you posted, it says:
PimpMyStremio server running at: http://127.0.0.1:5080

Just open http://127.0.0.1:5080/ in your browser, it's possible that the port (5080 in this case), may change if you restart PimpMyStremio, you can set the port to 5080 in PimpMyStremio's settings as you now know that is open for sure, so the port won't change in the link in the future.

The only bug here is the fact that it doesn't open the URL in the browser, but this is the first time I ever see it fail on a Windows system..

**Comment by sungshon** [comment]
Do you by any chance have no default browser set on your system? Or are you using Internet Explorer (or Edge) as your default browser?

It's possible that the OS doesn't return any executable path for a default browser at all, which is making the command that is meant to open in the default browser fail.

**Comment by sungshon** [comment]
See here, this command was attempted:

```
syscall: 'spawn cmd',
path: 'cmd',
spawnargs: [ '/c', 'start', '""', '/b', '/wait', 'http://127.0.0.1:5080' ] }
```

One of the arguments was `""`, which was supposed to contain the path to your default browser's executable file, but it's missing a path completely, so I suspect that your system is just not replying with one, try downloading Chrome (if you don't have it already) and setting it as the default browser, I think it could fix your issue completely.

**Comment by Aithaks** [comment]
Ok,will let you know on how it goes

**Comment by Aithaks** [comment]
Nope,I use chrome as the default browser and here is the updated output
C:\Windows\system32>"C:\***\***\Desktop\PimpMyStremio.exe" --verbose
PimpMyStremio - Checking for updates
PimpMyStremio - Already have latest version
PimpMyStremio - User defined add-ons list URL is valid, updating add-ons list
PimpMyStremio - Successfully updated add-ons list from remote source
PimpMyStremio server running at: http://127.0.0.1:8273
Non-critical: Could not auto-open webpage, presuming Linux OS
{ Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1317:13)
    at startup (bootstrap_node.js:240:16)
    at bootstrap_node.js:661:3
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [ '/c', 'start', '""', '/b', '/wait', 'http://127.0.0.1:8273' ] }
systrayhelper 0.0.5 (d5794e2a72a9cb160d78b6fd9ee640ad1df02af7 built 2018-12-05T0
9:24:27Z)
Process exit, code: 0
And how do I know which program is using the port? @sungshon

**Comment by sungshon** [comment]
@Aithaks

It doesn't matter what application is using that particular port, if you can't access the PimpMyStremio server in the browser in order to change the setting,  then you can use the method explained by @sleeyax in [his comment](https://github.com/sungshon/PimpMyStremio/issues/43#issuecomment-548767174), it just needs to be a different port, like `5080` (which we know is open)

I'm not sure how to fix opening in the browser for you.. I would need at least one more user to have the same problem as you do, so we can confirm this isn't a very isolated edge case, Win 7 should be supported though, @sleeyax said he tested it on a Win 7 VM and it worked for him.

So it must be some sort of isolated case on your system in particular, and I would need some way of reproducing it to be able to fix it.

**Comment by Aithaks** [comment]
Ok,I opened the server manually in my browser,but I can't seem to able download any addons,could you please help me out? @sungshon

**Comment by sungshon** [comment]
What do you mean by "I can't seem to able download any addons", do you mean the loading animation never stops? Are there any errors in the logs? Do you think there's any chance that some firewall may be blocking the download of the add-ons?

**Comment by Aithaks** [comment]
I meant that as soon as I click the download button,it disappears and nothing happens.No,I don't have any firewall,so there is no question of blocking anything and how do you obtain the logs,I am a noob to this and finally I do apologize for the inconvenience or if I have offended you in someway. @sungshon

**Comment by sungshon** [comment]
I am not offended, I am just surprised that so many things go wrong on your system. You get the logs like you did before, by running PimpMyStremio from the command line with the `--verbose` flag, and the logs will be showed in the command line.

Then trying to download an add-on, and checking the command line to see if there are any errors in the logs, or just pasting the entire log here as you did before.
