### ISSUE TITLE
Jackett pauses time to time

### ISSUE THREAD

**Issue by sezgit** [sungshon/PimpMyStremio#45]
Encountered this, the jackett addon will stop and pause time to time. The actual Jackett hasn't crashed thought. I'm running it on 1024MB device but Awesome everything works. Jackett just pauses time to time even if it running as the only one.

**Comment by sezgit** [comment]
Just did a reinstall, happened again but I tried the mono version and it worked. Weird, going close this

**Comment by sungshon** [comment]
If you run PimpMyStremio with `--verbose` from the terminal, it will print the logs in the terminal and thus see the add-on errors or the reasons the add-ons were stopped.

PimpMyStremio has some fail-safes to protect it's users, for example it will forcefully close an add-on if it is taking too long to start or even for taking too long to return streams.

I'm unsure if this is the case for Jackett in your scenario, but it's a possibility.
