### ISSUE TITLE
Add (dark) themes

### ISSUE THREAD

**Issue by sleeyax** [sungshon/PimpMyStremio#50]
It would be nice to have a dark theme to reduce eye strain, especially when using PMS at night. 

I've got a basic implementation of a theme switcher feature in [my themes branch](https://github.com/sleeyax/PimpMyStremio/tree/themes). At the moment it stores the current theme in local storage (and not in `PimpMyStremio-userConfig.json` because that would require an additional web request to the server resulting in a slow theme load).

You could add even more themes, or allow the user to customize it completely. I don't know how far you want to go with this, hence why I'm opening an issue first before creating a pull request.

![dark-theme-switcher](https://user-images.githubusercontent.com/30344294/71384442-94a60900-25e1-11ea-87fa-1564359fedb1.gif)

**Comment by sungshon** [comment]
This is really nice, I'm all for themes.

You should also check this line:
https://github.com/sungshon/PimpMyStremio/blob/master/src/web/index.html#L5

More specifically `orange-indigo` in that line, which indicates the material UI primary and secondary colors. You can see (and play with) the material UI preset colors here:
https://getmdl.io/customize/index.html

We could load this css file dynamically to change the primary and secondary colors of the UI.

My thinking is that themes should obviously have their custom CSS files, for full control over the UI, and also have default values for: background color, text color, primary color and secondary color. Regular users could then also influence the colors to these 4 settings in the settings menu if they wish.

**Comment by sungshon** [comment]
The one thing I'm not entirely sure about is if we should add a button to change light / dark in the header. What I'm worried about here is clogging the header with buttons, as the buttons use icons and are simplistic, the more there are of them, the more confusing it becomes for new users.

We could add a select box in the settings menu though, with options named as: "Light Theme", "Dark Theme", etc. It won't have that flip a switch feeling though..

**Comment by sungshon** [comment]
Btw, also customisation related, due to the very little actual unique text of the project, we could also easily add translation support..

**Comment by sungshon** [comment]
Also another fun idea, not sure how many users would really appreciate it though:

If I make the logo a SVG file, we could even have settings for logo primary / secondary colors :))

**Comment by sungshon** [comment]
@sleeyax Can you please create a PR for what you have now? So we have a starting point for this?

**Comment by sleeyax** [comment]
Ah yes, opened PR #56

**Comment by sungshon** [comment]
I've split this into 2 new tickets so it's easier to keep track of:
- https://github.com/sungshon/PimpMyStremio/issues/62
- https://github.com/sungshon/PimpMyStremio/issues/63
