### ISSUE TITLE
How to install on a Raspberry Pi 3?

### ISSUE THREAD

**Issue by chicungunya** [sungshon/PimpMyStremio#59]
Hi,
Please can you help me to install on a Raspberry Pi 3 with Raspbian ?
I tried this https://gist.github.com/sleeyax/e9635eb352a4fcdf94194f763d743689 (only part of install PMS) but I have errors.
Is there another way?
Thank you

**Comment by sungshon** [comment]
I never tried.. But basically, you should first install Node.js and NPM, then:
```
git clone https://github.com/sungshon/PimpMyStremio.git
cd PimpMyStremio/src
npm install
npm start
```

But PimpMyStremio is dependant on some binaries, namely: `youtube-dl` and `phantomjs`. So that might be a problem.. What errors are you getting?

**Comment by chicungunya** [comment]
> I never tried.. But basically, you should first install Node.js and NPM, then:
> 
> ```
> git clone https://github.com/sungshon/PimpMyStremio.git
> cd PimpMyStremio/src
> npm install
> npm start
> ```
> 
> But PimpMyStremio is dependant on some binaries, namely: `youtube-dl` and `phantomjs`. So that might be a problem.. What errors are you getting?

`pi@raspberrypi:~ $ cd PimpMyStremio/src
pi@raspberrypi:~/PimpMyStremio/src $ sudo npm install
(node:1047) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN package.json pimpmystremio@1.2.1 No repository field.
npm WARN package.json pimpmystremio@1.2.1 No README data
npm WARN deprecated m3u8-parsed@1.2.0: deprecated
npm ERR! git clone git@github.com:github:sungshon/m3u8-reader Clonage dans le dépôt nu '/root/.npm/_git-remotes/git-github-com-github-sungshon-m3u8-reader-e949026f'
npm ERR! git clone git@github.com:github:sungshon/m3u8-reader Permission denied (publickey).
npm ERR! git clone git@github.com:github:sungshon/m3u8-reader fatal: Impossilble de lire le dépôt distant.
npm ERR! git clone git@github.com:github:sungshon/m3u8-reader 
npm ERR! git clone git@github.com:github:sungshon/m3u8-reader Veuillez vérifier que vous avez les droits d'accès
npm ERR! git clone git@github.com:github:sungshon/m3u8-reader et que le dépôt existe.
npm ERR! git clone git@github.com:github:sungshon/node-auto-launch Clonage dans le dépôt nu '/root/.npm/_git-remotes/git-github-com-github-sungshon-node-auto-launch-763d75f6'
npm ERR! git clone git@github.com:github:sungshon/node-auto-launch Permission denied (publickey).
npm ERR! git clone git@github.com:github:sungshon/node-auto-launch fatal: Impossilble de lire le dépôt distant.
npm ERR! git clone git@github.com:github:sungshon/node-auto-launch 
npm ERR! git clone git@github.com:github:sungshon/node-auto-launch Veuillez vérifier que vous avez les droits d'accès
npm ERR! git clone git@github.com:github:sungshon/node-auto-launch et que le dépôt existe.
npm ERR! git clone git@github.com:github:sungshon/forked-systray Clonage dans le dépôt nu '/root/.npm/_git-remotes/git-github-com-github-sungshon-forked-systray-09fdcf73'
npm ERR! git clone git@github.com:github:sungshon/forked-systray Permission denied (publickey).
npm ERR! git clone git@github.com:github:sungshon/forked-systray fatal: Impossilble de lire le dépôt distant.
npm ERR! git clone git@github.com:github:sungshon/forked-systray 
npm ERR! git clone git@github.com:github:sungshon/forked-systray Veuillez vérifier que vous avez les droits d'accès
npm ERR! git clone git@github.com:github:sungshon/forked-systray et que le dépôt existe.
npm ERR! git clone git@github.com:github:sungshon/phantomjs-node Clonage dans le dépôt nu '/root/.npm/_git-remotes/git-github-com-github-sungshon-phantomjs-node-2bd3e0bb'
npm ERR! git clone git@github.com:github:sungshon/phantomjs-node Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
npm ERR! git clone git@github.com:github:sungshon/phantomjs-node Permission denied (publickey).
npm ERR! git clone git@github.com:github:sungshon/phantomjs-node fatal: Impossilble de lire le dépôt distant.
npm ERR! git clone git@github.com:github:sungshon/phantomjs-node 
npm ERR! git clone git@github.com:github:sungshon/phantomjs-node Veuillez vérifier que vous avez les droits d'accès
npm ERR! git clone git@github.com:github:sungshon/phantomjs-node et que le dépôt existe.
npm ERR! git clone git@github.com:github:sungshon/node-source-map-support Clonage dans le dépôt nu '/root/.npm/_git-remotes/git-github-com-github-sungshon-node-source-map-support-c65f1629'
npm ERR! git clone git@github.com:github:sungshon/node-source-map-support Permission denied (publickey).
npm ERR! git clone git@github.com:github:sungshon/node-source-map-support fatal: Impossilble de lire le dépôt distant.
npm ERR! git clone git@github.com:github:sungshon/node-source-map-support 
npm ERR! git clone git@github.com:github:sungshon/node-source-map-support Veuillez vérifier que vous avez les droits d'accès
npm ERR! git clone git@github.com:github:sungshon/node-source-map-support et que le dépôt existe.
npm ERR! notarget No compatible version found: m3u8-reader@'github:sungshon/m3u8-reader'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.0","1.1.0"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Linux 4.19.42-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/PimpMyStremio/src
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code ETARGET
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/PimpMyStremio/src/npm-debug.log
npm ERR! not ok code 0
pi@raspberrypi:~/PimpMyStremio/src $ npm start
(node:1075) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

> pimpmystremio@1.2.1 start /home/pi/PimpMyStremio/src
> node index.js

module.js:549
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/PimpMyStremio/src/index.js:3:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

npm ERR! pimpmystremio@1.2.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pimpmystremio@1.2.1 start script.
npm ERR! This is most likely a problem with the pimpmystremio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls pimpmystremio
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.19.42-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/PimpMyStremio/src
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/PimpMyStremio/src/npm-debug.log
npm ERR! not ok code 0
`

**Comment by sungshon** [comment]
You're getting `permission denied` errors on installation, do you have `git` installed?

**Comment by sungshon** [comment]
This was a git error, not a PimpMyStremio installation issue.. So I'm closing this to keep things clean.

If anyone will have issues installing on the RPI, they can open a new issue.
