### ISSUE TITLE
Emby and Plex not working

### ISSUE THREAD

**Issue by bilaliz** [sungshon/PimpMyStremio#70]
to start I can access emby and plex on their own just fine on my android box, but through stremio they dont work. 

I am on my s905x box and I have got PMS setup via the termux method, all addons are working except emby and plex
here are the errors i am getting. 
**emby client:** could not authenticate user _UNAME_ to server server-where-emby-is-located
and
**plex client:** could not get remote url or local address for server _NASname_, aborting connection attempt.

I reported this over at PMS Java but the dev said it is not a PMS java issue and that I should report it here.

**Comment by sungshon** [comment]
What is "PMS Java"?

Both Plex and Emby are addons, issues should be raised at their respective repositories:
- https://github.com/OwnGod/stremio-plex-client
- https://github.com/OwnGod/stremio-emby-client
