### ISSUE TITLE
Remote Access: LAN Issue

### ISSUE THREAD

**Issue by Frazz89** [sungshon/PimpMyStremio#75]
I installed PMS and got everything working fine.

I then went to change the remote access to LAN for access to other devices, and restarted. Since then I get the following message;

Error while starting PimpMyStremio

I cannot find a way to get back in to resolve this issue.

Attached screenshot.
![PMS Error](https://user-images.githubusercontent.com/63655079/79236616-16f25b80-7e65-11ea-8235-3d02909254a7.PNG)

**Comment by sungshon** [comment]
Interesting, I just tried the remote access setting and it still works fine for me.

What operating system are you using? Would you be willing to help me debug the issue?

**Comment by Frazz89** [comment]
Sure,

I am using Windows 10 (bootcamped from an iMac).

Let me know what you would like me to try and I will paste the results.

Thanks

**Comment by sungshon** [comment]
Can you open the folder with the PimpMyStremio executable in it in the command line? And then open it with `PimpMyStremio --verbose`?

This will show all the logs in the command line, and we can find out what is going wrong.

**Comment by Frazz89** [comment]
These are the logs from running the above;

PimpMyStremio - Checking for updates
PimpMyStremio - Already have latest version
PimpMyStremio - User defined add-ons list URL is valid, updating add-ons list
PimpMyStremio - Successfully updated add-ons list from remote source
Remote access choice: LAN
Domain IP: 192.168.1.140
Domain: 192-168-1-140.519b6502d940.stremio.rocks
Add-on running: booblyboo/stremio-zooqle-local
Add-on running: BoredLama/stremio-jackett-local
PimpMyStremio server running at: https://192-168-1-140.519b6502d940.stremio.rocks:7777
systrayhelper 0.0.5 (d5794e2a72a9cb160d78b6fd9ee640ad1df02af7 built 2018-12-05T09:24:27Z)

**Comment by sungshon** [comment]
There don't seem to be errors here.. what happens if you open https://192-168-1-140.519b6502d940.stremio.rocks:7777 in your browser?

**Comment by Frazz89** [comment]
![error](https://user-images.githubusercontent.com/63655079/79241177-9cc4d580-7e6a-11ea-8ff3-d6aed5f04f0c.png)

Just this

**Comment by sungshon** [comment]
Are you sure u started it with `--verbose`? It might be that it just shows the loader logs.. which happens if you don't start it as verbose..

**Comment by sungshon** [comment]
Also, are you using a VPN by any chance?

**Comment by Frazz89** [comment]
No VPN, just connected to my home WiFi, I have screenshoted what I input into CMD, in case I entered something incorrectly.
![Erro 2](https://user-images.githubusercontent.com/63655079/79242415-380a7a80-7e6c-11ea-9178-846ea9c23d17.PNG)

**Comment by sungshon** [comment]
This is all quite interesting, there are absolutely no errors in these logs.

Can you open the Developer Tools on the updater page (from the browser) by right clicking on the page, and selecting Inspect, then in the new window, press the "Console" tab, I believe there should be an error visible there.

**Comment by Frazz89** [comment]
This is the error:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://192-168-1-140.519b6502d940.stremio.rocks:7777/loading-api. (Reason: CORS request did not succeed).

**Comment by sungshon** [comment]
rofl

**Comment by Frazz89** [comment]
This is the log:

{…}
​
abort: function abort(e)
​
always: function always()
​
catch: function catch(e)
​
done: function add()
​
fail: function add()
​
getAllResponseHeaders: function getAllResponseHeaders()
​
getResponseHeader: function getResponseHeader(e)
​
overrideMimeType: function overrideMimeType(e)
​
pipe: function pipe()
​
progress: function add()
​
promise: function promise(e)
​
readyState: 0
​
setRequestHeader: function setRequestHeader(e, t)
​
state: function state()
​
status: 0
​
statusCode: function statusCode(e)
​
statusText: "error"
​
then: function then(t, r, i)
​
<prototype>: Object { … }
loader:70:19


Dunno if you need this bit or not!

**Comment by sungshon** [comment]
what browser are you using?

**Comment by Frazz89** [comment]
Firefox

**Comment by sungshon** [comment]
When I saw the CORS error, I really thought it was an issue on my end for forgetting to set CORS in the headers, but I do set CORS in the header correctly, so it can't be that..

**Comment by sungshon** [comment]
One more thing, in your command line, can you do:
```
ping 192-168-1-140.519b6502d940.stremio.rocks
```
and paste the result here?

**Comment by Frazz89** [comment]
checking in Chrome I get the following error;

Failed to load resource: net::ERR_NAME_NOT_RESOLVED

https://192-168-1-140.519b6502d940.stremio.rocks:52356/loading-api

**Comment by Frazz89** [comment]
for ping I got:

Ping request could not find host 192-168-1-140.519b6502d940.stremio.rocks. Please check the name and try again.

**Comment by sungshon** [comment]
you see, that's the issue right there, when i do:
```
PING 192-168-1-140.519b6502d940.stremio.rocks (192.168.1.140): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
ping: sendto: No route to host
Request timeout for icmp_seq 4
```
notice: `192-168-1-140.519b6502d940.stremio.rocks (192.168.1.140)`

this means that the domain resolves correctly to an IP for me, but does not for you.

did you by any chance change your DNS settings in Windows to something else?

**Comment by Frazz89** [comment]
No, I havent changed anything as far as I am aware.

I installed PMS and it was working as expected until I tried to change remote access to LAN.

When I tried to save and restart I got the above issue.

The only things I have done since then is end the Node.js tasks in task manager, closing Stremio in task manager, and the same with Jackett and restart the PC.

**Comment by sungshon** [comment]
Ok, can you change the DNS settings in Windows to Google or Cloudflare? there are many articles on the internet explaining how to do this, it is not hard. And then try to open PMS again.

**Comment by Frazz89** [comment]
Changed to Google DNS and then disconnected and reconnected to my wifi, same problem :(

**Comment by sungshon** [comment]
can you do:
```
ping 192-168-1-140.519b6502d940.stremio.rocks
```
again?

**Comment by Frazz89** [comment]
Tried CloudFare too and getting the same issue.

Pinging just gives the same;

Ping request could not find host 192-168-1-140.519b6502d940.stremio.rocks. Please check the name and try again.

No idea what I have done to cause such an issue!

**Comment by sungshon** [comment]
Do you have any other device in the house? Can you try to go to:
https://192-168-1-140.519b6502d940.stremio.rocks:7777

From another device? Phone.. Tablet.. a different computer, whatever.. While PMS is running (and even if it still shows that error in the browser)

**Comment by sungshon** [comment]
Uhm, I have another idea, try this:
https://www.my-private-network.co.uk/kbhome/how-to-disable-ipv6-on-windows-10/

**Comment by Frazz89** [comment]
So I think its fixed!

I ended all the JS Nodes again from all the instances I have been trying to open PMS.

I have now been able to access it again (possible due to using the cloudfare DNS?)

One thing in settings I can see I never input a server password - could this have caused it? I am guessing I should have something in there?

**Comment by Frazz89** [comment]
interestingly, if I ping the same address that I opened I still get the same error?

**Comment by sungshon** [comment]
Try what i linked above:
https://www.my-private-network.co.uk/kbhome/how-to-disable-ipv6-on-windows-10/

**Comment by Frazz89** [comment]
That seems to have fixed it, I can get on fine now from testing.

Thanks a lot for your help!

Do I need to leave IPV6 disabled?

**Comment by sungshon** [comment]
Yes, this is the reason it caused DNS issues in the first place, there is no real need to have ipv6 support.. your internet will work fine without it, i don't even have ipv6, never did..
