### ISSUE TITLE
Discord addon problem

### ISSUE THREAD

**Issue by KalyterosV2** [sungshon/PimpMyStremio#81]
As you can see in the screenshots i'm playing an episode in stremio but in the discord it does't show the name of the tv show
![image](https://user-images.githubusercontent.com/68316399/87506157-035fb800-c641-11ea-8a5e-f89d739796ae.png)
![image](https://user-images.githubusercontent.com/68316399/87506184-0f4b7a00-c641-11ea-8579-8b4775c9b9f9.png)

**Comment by sleeyax** [comment]
Hi, please open an issue at the local [discord RP addon](https://github.com/sleeyax/stremio-discord) github repo and close this one here. Keep in mind that PMS only provides local addons from the community and is not 'responsible' if an addon breaks.
