### ISSUE TITLE
[Feature request] Docker support

### ISSUE THREAD

**Issue by fidelix** [sungshon/PimpMyStremio#82]
Would be a pretty easy way to keep it alive for people who have servers.

**Comment by fidelix** [comment]
Tried to do it myself. It starts up with an error (due to systray) but it works.

Try:
`docker run -v /my/dir/:/root/.local/share/PimpMyStremio/ fidelix/pimpmystremio`
Then check http://localhost:7777

This would become a lot cleaner if PimpMyStremio adds an option to specify port, location of settings directory and a "headless" mode on the startup command (to avoid tray and opening the browser).

**Comment by sungshon** [comment]
What Dockerfile did you use to build it?

> This would become a lot cleaner if PimpMyStremio added an option to specify port, location of settings directory and a "headless" mode on the startup command (to avoid tray and opening the browser).

I can add command line arguments to specify the port, location of settings directory and a headless mode, it shouldn't be hard.

I'm up to making a docker image.

**Comment by fidelix** [comment]
```
FROM lsiobase/ubuntu:bionic
WORKDIR /app
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -qq -y unzip curl
RUN curl -L -O https://github.com/sungshon/PimpMyStremio/releases/download/v1.2.2/PimpMyStremio-linux.zip
RUN unzip -j PimpMyStremio-linux.zip
RUN ls -la /app/
RUN chmod +x /app/PimpMyStremio
EXPOSE 7777
VOLUME /root/.local/share/PimpMyStremio/
ENTRYPOINT ["/app/PimpMyStremio"]
```

**Comment by BeatLink** [comment]
Super interested in this, I run my home server and it would be really easy to manage as a docker container that can be accessed remotely.

**Comment by sleeyax** [comment]
> Tried Alpine, but it simply doesn't work. It gives a bizarre error when executing the entrypoint.
> "standard_init_linux.go:211: exec user process caused "no such file or directory"

That's because the PMS linux binary is linked against GNU libc and Alpine uses musl libc, so it will not work. You can confirm this by installing and running `file` on the binary:
```
/app # file PimpMyStremio
PimpMyStremio: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, BuildID[sha1]=05ec200467657de71de5edd9f18e14bee2ec9a83, with debug_info, not stripped
```
See [this issue](https://github.com/gliderlabs/docker-alpine/issues/219) on the Alpine repo for more info.

**Comment by sleeyax** [comment]
PimpMyStremio's packager supports alpine as a build target out of the box, so if my PR gets approved and a new build published, we could get it to work on Alpine without any workarounds :)

**Comment by sleeyax** [comment]
Forget that, I got it working using an [alpine-glibc](https://hub.docker.com/r/frolvlad/alpine-glibc) image. Execute `docker run -p 7777:7777 sleeyax/pimpmystremio` to give it a spin.

**Comment by sungshon** [comment]
@sleeyax Any chance you could make a PR with the Dockerfile? I could publish an official Docker image for PMS if u make a PR.

**Comment by sleeyax** [comment]
@sungshon sure, Ill create a PR in a moment

**Comment by sleeyax** [comment]
For reference: PR https://github.com/sungshon/PimpMyStremio/pull/85 opened.

**Comment by sungshon** [comment]
@sleeyax thanks!
