### ISSUE TITLE
Cannot get jackett working

### ISSUE THREAD

**Issue by adocampo** [sungshon/PimpMyStremio#84]
First, thank you for PMS, just discovered when Juan Carlos2 addon stopped working.

I have a docker container on my home server with jackett, transmission, medusa, and plex, so it downloads everything I want just perfect, but I would like to see "on demand" those torrents through stremio. 

On my PC, I've installed PMS, and configured jackett addon like this:
![image](https://user-images.githubusercontent.com/2266612/93649477-62102c00-fa0c-11ea-810c-e062b43c9ade.png)

On the output I see the addon is loaded on PMS
```
$ ./PimpMyStremio 
PimpMyStremio - Checking for updates
PimpMyStremio - Already have latest version
PimpMyStremio - User defined add-ons list URL is valid, updating add-ons list
PimpMyStremio - Successfully updated add-ons list from remote source
Remote access choice: No (local)
Add-on running: BoredLama/stremio-jackett-local
PimpMyStremio server running at: http://127.0.0.1:7777
systrayhelper 0.0.5 (d5794e2a72a9cb160d78b6fd9ee640ad1df02af7 built 2018-12-05T09:24:55Z)
```

Then, copied the Addon URL (http://127.0.0.1:7777/stremio-jackett-local/manifest.json) and pasted on "Play URL/Magnet link"
![image](https://user-images.githubusercontent.com/2266612/93649570-9388f780-fa0c-11ea-8778-dabb21385639.png)
I click on "Install"
![image](https://user-images.githubusercontent.com/2266612/93650287-689fa300-fa0e-11ea-9b54-a8814b71a958.png)
And I can see it on my installed addons
![image](https://user-images.githubusercontent.com/2266612/93650326-83721780-fa0e-11ea-92c2-e562735eb9bc.png)

So, let's do some test. First I did a search on Jackett, to see there are results
![image](https://user-images.githubusercontent.com/2266612/93650425-bfa57800-fa0e-11ea-855e-ddf265e16ed5.png)

And search for the same tv show on stremio, and select any episode, then the message ADD-ON JACKETT IS STILL LOADING appears
![image](https://user-images.githubusercontent.com/2266612/93650513-ff6c5f80-fa0e-11ea-956d-9ad7911a454f.png)

I wait then until the message disappears, but no jackett source appears to select from... 

I'm doing anything wrong? How can I see what's happening? Do I need to run jackett on the same host as PMS and Stremio?

Thank you!

**Comment by adocampo** [comment]
Just noticed that after waiting for loading Jackett add-on, then it stops on PMS
![image](https://user-images.githubusercontent.com/2266612/93651744-e2d22680-fa12-11ea-84de-574c53b0e34b.png)

**Comment by sungshon** [comment]
Uhm, sounds like something broke in the addon, you should create an issue about it on the repository for the jackett addon: https://github.com/BoredLama/stremio-jackett-local/issues

**Comment by adocampo** [comment]
Thank you @sungshon for pointing there, I didn't notice that repo.
I'm opening an issue there and closing this one.
