### ISSUE TITLE
"Load in Stremio app" not working on Linux (Kubuntu)

### ISSUE THREAD

**Issue by ccrowles** [sungshon/PimpMyStremio#86]
Stremio version: 4.4.116
PimpMyStremio version: 1.2.2
Browser: Vivaldi Browser 3.3.2022.45

When I click on the "load in Stremio app" I always get this error:
![Screenshot_2020_43_09-20-20_220925](https://user-images.githubusercontent.com/12866474/93721811-bc3af980-fb92-11ea-8597-86d733938257.jpg)

I get it twice in a row, for some reason.

How can I fix this?

**Comment by sungshon** [comment]
It looks like Stremio on Kubuntu might not associate with the `stremio://` protocol for some reason. Change `stremio://` to `http://` in the url from your error, then open Stremio and paste the link (with `http://`) in the search field (the normal search field that you use to search in Stremio) and press Enter. This should load the catalog in Stremio. (the manual way)

**Comment by ccrowles** [comment]
@sungshon I pasted it in the addons search field (because I didn't read properly) but it actually worked! It asked me to install the addons I had enabled in PMS. Thank you so much!

**Comment by sungshon** [comment]
np, glad it works. There's nothing we can do about associating `stremio://` with the Stremio app from PMS though.. but you could create a `desktop` file for it manually that associates the `stremio://` protocol and register it for Stremio if you want, that will make `stremio://` links work correctly. You can google "linux desktop file" for more info.
