### ISSUE TITLE
Support MOCHs (multi file hosters)

### ISSUE THREAD

**Issue by sungshon** [sungshon/PimpMyStremio#9]
Like Real Debrid, Premiumizer, etc.

**Comment by sungshon** [comment]
The only way I see this being done, considering that extractors are in add-ons and not in PMS, is to create an internal module that is shared to add-ons and can convert video URLs to URLs that MOCHs respond with for them.

The MOCH API implementation makes sense to be in PMS and shared to add-ons, to avoid add-ons implementing this on their side leading to bloated code in add-ons.

**Comment by sungshon** [comment]
The more I think of this the stupider it gets, MOCHs should be implemented in Stremio directly, to support all add-ons, an implementation in PMS is unnecessary.

Switching to `maybe` tag, although I don't see the logic in doing it anymore.

**Comment by sungshon** [comment]
I'm thinking this might be better as a separate PMS add-on. (or even a remote add-on)

Afaik MOCH services convert one link (even a magnet link) to another.

So a proxy add-on (like the IMDB ones) could take in any other add-on link and convert all it's stream sources to MOCH converted ones.

So the only configurable settings in the add-on should be giving an access token and a link to a different add-on that you want to add MOCH support to, then waiting for any stream request and feeding the `url` of the stream to a specific MOCH service.

The issue with this, is that normally an add-on would take in only 1 link, while people might want all their content MOCHed. (which can only happen if Stremio supports MOCHs directly)

The problem with making this a remote add-on (as opposed to being only a local add-on) is the security implications of the access token, which would normally be passed as part of the URL (ie: `https://something.com/access-token/manifest.json`)

Further research / thinking about this might be required in the future as a complete solution is currently unavailable. But an add-on makes sense for now.

**Comment by sleeyax** [comment]
Don't worry, I know javascript basics lol it's just easy to overlook.

**Comment by doingodswork** [comment]
Just in case anyone is stumbling upon this thread: I worked on a debrid addon for Stremio in the recent months for the addon competition. Until today only some private beta testers used the addon, but today I put up a website with installation instructions for the public: https://www.deflix.tv

@sungshon: I haven't tried running it with PMS yet. If there's anything I have to customize, let me know :)

**Comment by sungshon** [comment]
@sungshon 
Thank you for commenting. I think I may finally be able to remove this ticket.

Using PimpMyStremio is just like making serverless addons, the only limitations are:
- addon needs to be written in Node.js
- addon needs to use only the [whitelisted modules](https://github.com/sungshon/PimpMyStremio/blob/master/docs/modules-whitelist.md) and / or [internal modules](https://github.com/sungshon/PimpMyStremio/blob/master/docs/modules-internal.md)
